#ifndef _TRIGGER_H_
#define _TRIGGER_H_

#include <Windows.h>
#include <stdio.h>
#include "..\..\Library\AXL(Library)\C, C++\AXL.h"
#include "..\..\Library\AXL(Library)\C, C++\AXC.h"
#include "..\..\Library\AXL(Library)\C, C++\AXHS.h"
#include "..\..\Library\AXL(Library)\C, C++\AXDev.h"	// AxcKe*CommandData16, used by the periodic trigger


#pragma once

// These five live in the "For CNT_RECAT_SC_10" section of AXC.h:
//
//   AxcTriggerSetEncoderInput      AxcTriggerSetTriggerCountClear
//   AxcTriggerSetTriggerOutport    AxcTriggerReadTriggerCount
//   AxcTriggerGetTriggerOutport
//
// They used to be compiled out behind AXL_HAS_CNT_RECAT_TRIGGER_API, on the
// assumption that the installed AXL did not have them. It does: the AXL.dll
// and AXL.lib under Library/ both export all five. Compiling them out meant
// AxcTriggerSetTriggerOutport was never called, so no channel ever routed its
// trigger to a physical output pin, and AxcTriggerReadTriggerCount - the one
// way to ask the board how many pulses it actually emitted - was unavailable.
//
// They are now resolved from the loaded AXL.dll at construction instead of
// being linked. A site with an older AXL loses these calls and says so in the
// log, rather than failing to start at all, which is what implicit linking to
// a missing export would do.

// Configuration for the position-period (periodic mode) line scan trigger.
//
// All distances use the unit established by dMoveUnitPerPulse, so passing
// dMoveUnitPerPulse in mm per encoder count makes every other distance mm.
//
// dPitch must land on a whole number of encoder counts. The hardware
// comparator works in integer counts, so a fractional pitch is rounded and
// the average pitch drifts away from the optical pitch for the whole scan.
struct PERIODIC_TRIG_CFG
{
	long   lChannelNo;			// counter channel, 0 .. (channel count - 1)
	DWORD  dwEncoderInput;		// which of the 4 encoder inputs feeds this channel
	DWORD  dwTriggerOutPort;	// output port bitmask, bit0 = Trigger Out 0
	double dMoveUnitPerPulse;	// distance per encoder count   (0.001  = 1.0 um)
	double dPitch;				// trigger pitch                (0.005   = 5.0 um)
	double dScanStart;			// trigger block lower position
	double dScanEnd;			// trigger block upper position
	double dPulseWidthUS;		// pulse width [us], camera minimum is 1.0
	DWORD  dwTriggerLevel;		// 0 = low active, 1 = high active
	DWORD  dwDirectionCheck;	// 0 = both directions, 1 = count up only, 2 = count down only
	bool   bEncReverse;			// reverse the encoder count direction

	PERIODIC_TRIG_CFG()
		: lChannelNo(0)
		, dwEncoderInput(0)
		, dwTriggerOutPort(0x1)
		, dMoveUnitPerPulse(0.001)		// 1.0 um per count
		, dPitch(0.005)					// 5.0 um  -> 5 counts
		, dScanStart(0.0)
		, dScanEnd(0.0)
		, dPulseWidthUS(2.0)
		, dwTriggerLevel(1)
		, dwDirectionCheck(1)
		, bEncReverse(false)
	{
	}
};

class CAjinTrigger
{
private:
	long lCntChannelCounts;

	// True when dPitch is a whole number of encoder counts. Reports the count
	// and, when it is not whole, the relative error rounding would introduce.
	static bool IsPitchIntegerCounts(double dPitch, double dUPP,
									 double* dpCounts, double* dpErrorRatio);

	bool IsChannelValid(long lChannelNo) const;

public:
	// Trigger positions the vector-table StartTrigger() can hold. Ties the
	// bound check to the fixed arrays inside it so the two cannot drift apart.
	static const int MAX_TRIGGER_POS = 10;

	CAjinTrigger();
	~CAjinTrigger();

	long GetChannelCount() const { return lCntChannelCounts; }

	// ---- vector table (RANGE) trigger -----------------------------------
	// For a handful of discrete snap positions. Not usable for a line scan:
	// the position table holds at most MAX_TRIGGER_POS entries.
	bool SetTriggerActPos(int nTableNo, double fActPos , double fUPP);
	bool SetTriggerEncReverse(int nTableNo, bool bRevers);

	bool SetTriggerOnOff(int nModNo, int nTableNo, bool bEnable);
	bool SetTriggerOutPort(int nModNo, int nTableNo, int nTrigOutPortNo);
	bool SetTriggerConfig(int nModNo, int nTableNo, int nEncoderPortNo, int nTrigOutPortNo, double fPulsWidthUS);
	bool StartTrigger(int nModNo, int nTableNo, int nTrigCount, double fTrigStartPos, double fTrigDistance);

	// ---- periodic mode --------------------------------------------------
	// Continuous position synchronised trigger for line scan / TDI imaging.
	// The pulse train is generated by the counter hardware, so it uses no
	// position buffer and the number of triggers per scan is unbounded.
	bool StartPeriodicTrigger(const PERIODIC_TRIG_CFG& cfg);
	bool StopPeriodicTrigger(long lChannelNo);

	// Zero (or preset) the counter before a scan so the block positions in
	// PERIODIC_TRIG_CFG are relative to the scan origin.
	bool ResetScanOrigin(long lChannelNo, double dPos = 0.0);

	bool GetActPos(long lChannelNo, double* dpPos);

	// ---- commissioning helpers ------------------------------------------
	bool ClearTriggerCount(long lChannelNo);
	bool ReadTriggerCount(long lChannelNo, long* lpCount);

	// Which of the optional calls this AXL turned out to have. Resolved once,
	// at construction, and reported in the log there.
	static bool HasOutportApi();
	static bool HasTriggerCountApi();

	// Route this channel's trigger to output port(s). dwMask bit 0 is Trigger
	// Out 0. Returns false when the call is missing from this AXL.
	bool SetTriggerOutPortMask(long lChannelNo, DWORD dwMask);

	// Print what the board holds, read back from the board rather than from
	// the struct that was written to it. The two disagreeing is the whole
	// point: a call can return success and leave the register unchanged.
	void ReportChannelConfig(long lChannelNo, const char* pszWhen);

	// Bit 2 of AxcStatusGetChannel - the trigger output line as the board
	// sees it, which is the closest thing to an oscilloscope in software.
	bool ReadOutputState(long lChannelNo, bool* pbOn);

	// Drive the trigger output directly, ignoring the encoder entirely. This
	// identifies the pin on a scope and proves the output stage on its own,
	// separately from every encoder and comparator setting.
	//
	// Does not sleep: hold each level long enough to see by calling it from a
	// cycle that already has a timer, not by blocking a communication thread.
	bool ForceOutput(long lChannelNo, bool bOn);

	// Relative pitch error from a measured scan: clear the count, travel
	// dTravel, read the count back. Returns (measured - configured) / configured.
	static double CalcPitchError(double dTravel, long lTrigCount, double dPitch);
};

#endif
