#ifndef _TRIGGER_H_
#define _TRIGGER_H_

#include <Windows.h>
#include <stdio.h>
#include "..\..\Library\AXL(Library)\C, C++\AXL.h"
#include "..\..\Library\AXL(Library)\C, C++\AXC.h"
#include "..\..\Library\AXL(Library)\C, C++\AXHS.h"


#pragma once

// The four routing / counting calls below live in the "For CNT_RECAT_SC_10"
// section of AXC.h and are absent from AXL 4.2.0.2, the version shipped with
// the EzSoftware installed on this machine:
//
//   AxcTriggerSetEncoderInput      AxcTriggerSetTriggerCountClear
//   AxcTriggerSetTriggerOutport    AxcTriggerReadTriggerCount
//
// SIO-HPC4 does not need the first two - each counter channel is wired to its
// own encoder input and trigger output, so there is nothing to route. Set this
// to 1 only on a site running a newer AXL with a CNT_RECAT_SC_10 module.
#ifndef AXL_HAS_CNT_RECAT_TRIGGER_API
#define AXL_HAS_CNT_RECAT_TRIGGER_API 0
#endif

// Configuration for the position-period (periodic mode) line scan trigger.
//
// All distances use the unit established by dMoveUnitPerPulse, so passing
// dMoveUnitPerPulse in mm per encoder count makes every other distance mm.
//
// dPitch must land on a whole number of encoder counts. The hardware
// comparator works in integer counts, so a fractional pitch is rounded and
// the average pitch drifts away from the optical pitch for the whole scan.
struct PERIODIC_TRIG_CFG
{
	long   lChannelNo;			// counter channel, 0 .. (channel count - 1)
	DWORD  dwEncoderInput;		// which of the 4 encoder inputs feeds this channel
	DWORD  dwTriggerOutPort;	// output port bitmask, bit0 = Trigger Out 0
	double dMoveUnitPerPulse;	// distance per encoder count   (0.0001 = 0.1 um)
	double dPitch;				// trigger pitch                (0.005   = 5.0 um)
	double dScanStart;			// trigger block lower position
	double dScanEnd;			// trigger block upper position
	double dPulseWidthUS;		// pulse width [us], camera minimum is 1.0
	DWORD  dwTriggerLevel;		// 0 = low active, 1 = high active
	DWORD  dwDirectionCheck;	// 0 = both directions, 1 = count up only, 2 = count down only
	bool   bEncReverse;			// reverse the encoder count direction

	PERIODIC_TRIG_CFG()
		: lChannelNo(0)
		, dwEncoderInput(0)
		, dwTriggerOutPort(0x1)
		, dMoveUnitPerPulse(0.0001)		// 0.1 um per count
		, dPitch(0.005)					// 5.0 um  -> 50 counts
		, dScanStart(0.0)
		, dScanEnd(0.0)
		, dPulseWidthUS(2.0)
		, dwTriggerLevel(1)
		, dwDirectionCheck(1)
		, bEncReverse(false)
	{
	}
};

class CAjinTrigger
{
private:
	long lCntChannelCounts;

	// True when dPitch is a whole number of encoder counts. Reports the count
	// and, when it is not whole, the relative error rounding would introduce.
	static bool IsPitchIntegerCounts(double dPitch, double dUPP,
									 double* dpCounts, double* dpErrorRatio);

	bool IsChannelValid(long lChannelNo) const;

public:
	// Trigger positions the vector-table StartTrigger() can hold. Ties the
	// bound check to the fixed arrays inside it so the two cannot drift apart.
	static const int MAX_TRIGGER_POS = 10;

	CAjinTrigger();
	~CAjinTrigger();

	long GetChannelCount() const { return lCntChannelCounts; }

	// ---- vector table (RANGE) trigger -----------------------------------
	// For a handful of discrete snap positions. Not usable for a line scan:
	// the position table holds at most MAX_TRIGGER_POS entries.
	bool SetTriggerActPos(int nTableNo, double fActPos , double fUPP);
	bool SetTriggerEncReverse(int nTableNo, bool bRevers);

	bool SetTriggerOnOff(int nModNo, int nTableNo, bool bEnable);
	bool SetTriggerOutPort(int nModNo, int nTableNo, int nTrigOutPortNo);
	bool SetTriggerConfig(int nModNo, int nTableNo, int nEncoderPortNo, int nTrigOutPortNo, double fPulsWidthUS);
	bool StartTrigger(int nModNo, int nTableNo, int nTrigCount, double fTrigStartPos, double fTrigDistance);

	// ---- periodic mode --------------------------------------------------
	// Continuous position synchronised trigger for line scan / TDI imaging.
	// The pulse train is generated by the counter hardware, so it uses no
	// position buffer and the number of triggers per scan is unbounded.
	bool StartPeriodicTrigger(const PERIODIC_TRIG_CFG& cfg);
	bool StopPeriodicTrigger(long lChannelNo);

	// Zero (or preset) the counter before a scan so the block positions in
	// PERIODIC_TRIG_CFG are relative to the scan origin.
	bool ResetScanOrigin(long lChannelNo, double dPos = 0.0);

	bool GetActPos(long lChannelNo, double* dpPos);

	// ---- commissioning helpers ------------------------------------------
	bool ClearTriggerCount(long lChannelNo);
	bool ReadTriggerCount(long lChannelNo, long* lpCount);

	// Relative pitch error from a measured scan: clear the count, travel
	// dTravel, read the count back. Returns (measured - configured) / configured.
	static double CalcPitchError(double dTravel, long lTrigCount, double dPitch);
};

#endif
